Components
Patfarmurs/math-magicians pull request #2
Opened 2023-01-20 13:33 UTC by Patfarmurs

## In this milestone I : 
>- Add components to a calculator

2023-01-20 17:58 UTC, Lucas-Masaba requested changes
# Hello @Patfarmurs  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Successfully implemented most requirements 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Please delete the `App.test.js` file in your project(The tests do not match the current project and would fail.). You are required to remove the boilerplate template and this file is one of them.

- [ ] In your `README.md`, please customise your feature features header to suit your project. Currently, it has default values
![image](https://user-images.githubusercontent.com/45460192/213773034-97d677b2-e855-4226-9c38-448b6ac52657.png)

2023-01-20 17:58 UTC, Lucas-Masaba commented on src/components/Calculator.js
> +  );
- [ ] Please design your calculator to match the design provided.
### Your implementation
![image](https://user-images.githubusercontent.com/45460192/213772376-c47bbb50-94ba-4e29-9b50-8eb09d339d47.png)
### Required
![image](https://user-images.githubusercontent.com/45460192/213772457-063422a0-edc6-47f7-9d49-8e79344b6b79.png)

2023-01-20 23:43 UTC, Patfarmurs commented on src/components/Calculator.js
> +  );
Thanks, @Lucas-Masaba for your feedback.

2023-01-21 00:10 UTC, franclobo requested changes
Hi @Patfarmurs, 

# ♻️ Required Changes ♻️

![soClose](https://user-images.githubusercontent.com/58642949/213827766-42185e04-32a7-4550-b02f-84ce6a32c730.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors ✔️ 
- Correct git flow ✔️ 
- Professional README file ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 00:10 UTC, franclobo commented on src/components/Calculator.js
> +          <button type="submit" onClick={(event) => handleClick(event, state, setter)} className="zero">0</button>
- [ ] Well done implementing the changes requested by the last code reviewer, but take in mind the zero on the display is not a button, please fix it for a better user experience 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/213827298-f1924ddc-5362-4d15-b21c-418cc45c7f62.png)

2023-01-21 00:21 UTC, Patfarmurs commented on src/components/Calculator.js
> +          <button type="submit" onClick={(event) => handleClick(event, state, setter)} className="zero">0</button>
@franclobo I did not understand your comment, would you please be more clear.

2023-01-21 06:51 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @Patfarmurs        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: aa
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R
- [x] Nice UI Design







 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2023-01-21 17:45 UTC, merged